#ifndef UI_LAYOUT_SEARCHING_H
#define UI_LAYOUT_SEARCHING_H

#define UI_SEARCH_LCD_WIDTH 320
#define UI_SEARCH_LCD_HEIGHT 240

#define UI_SEARCH_ARENA_HEIGHT 160
#define UI_SEARCH_ARENA_Y 0

#define UI_SEARCH_PET_X 124
#define UI_SEARCH_PET_Y 23
#define UI_SEARCH_PET_W 72
#define UI_SEARCH_PET_H 97

#define UI_SEARCH_FLOOR_Y 120
#define UI_SEARCH_FLOOR_TILE_W 70
#define UI_SEARCH_FLOOR_TILE_H 70
#define UI_SEARCH_FLOOR_TILE_COUNT 5

#define UI_SEARCH_LOG_X 10
#define UI_SEARCH_LOG_Y 10

#define UI_SEARCH_STATS_HEIGHT 80
#define UI_SEARCH_STATS_Y 160

#define UI_SEARCH_PET_NAME_X 5
#define UI_SEARCH_PET_NAME_Y 2

#define UI_SEARCH_PET_LEVEL_X 5
#define UI_SEARCH_PET_LEVEL_Y 20

#define UI_SEARCH_PET_DP_X 5
#define UI_SEARCH_PET_DP_Y 38

#define UI_SEARCH_BARS_X 160
#define UI_SEARCH_BARS_WIDTH 150

#define UI_SEARCH_HP_TEXT_Y 2
#define UI_SEARCH_HP_BAR_Y 12
#define UI_SEARCH_HP_BAR_H 6

#define UI_SEARCH_EN_TEXT_Y 20
#define UI_SEARCH_EN_BAR_Y 30
#define UI_SEARCH_EN_BAR_H 6

#define UI_SEARCH_XP_TEXT_Y 38
#define UI_SEARCH_XP_BAR_Y 48
#define UI_SEARCH_XP_BAR_H 4

#define UI_SEARCH_STATS_LINE_Y 56

#define UI_SEARCH_STATS_TEXT_X 5
#define UI_SEARCH_STATS_TEXT_Y 60

#endif
