#ifndef UI_LAYOUT_GAME_H
#define UI_LAYOUT_GAME_H

#define UI_GAME_LCD_WIDTH 320
#define UI_GAME_LCD_HEIGHT 240

#define UI_GAME_ARENA_HEIGHT 160
#define UI_GAME_ARENA_Y 0

#define UI_GAME_PET_X 40
#define UI_GAME_PET_Y 50
#define UI_GAME_PET_W 72
#define UI_GAME_PET_H 97

#define UI_GAME_PET_SHADOW_X 46
#define UI_GAME_PET_SHADOW_Y 145
#define UI_GAME_PET_SHADOW_W 60
#define UI_GAME_PET_SHADOW_H 10

#define UI_GAME_ENEMY_X 220
#define UI_GAME_ENEMY_Y 60
#define UI_GAME_ENEMY_W 50
#define UI_GAME_ENEMY_H 28

#define UI_GAME_ENEMY_SHADOW_X 222
#define UI_GAME_ENEMY_SHADOW_Y 86
#define UI_GAME_ENEMY_SHADOW_W 45
#define UI_GAME_ENEMY_SHADOW_H 8

#define UI_GAME_ENEMY_DAMAGE_X 230
#define UI_GAME_ENEMY_DAMAGE_Y 35

#define UI_GAME_PET_EXP_X 40
#define UI_GAME_PET_EXP_Y 25

#define UI_GAME_ENEMY_NAME_X 210
#define UI_GAME_ENEMY_NAME_Y 95

#define UI_GAME_ENEMY_HP_BAR_X 210
#define UI_GAME_ENEMY_HP_BAR_Y 110
#define UI_GAME_ENEMY_HP_BAR_W 70
#define UI_GAME_ENEMY_HP_BAR_H 8

#define UI_GAME_COMBAT_LOG_X 10
#define UI_GAME_COMBAT_LOG_Y 10

#define UI_GAME_STATS_HEIGHT 80
#define UI_GAME_STATS_Y 160

#define UI_GAME_PET_NAME_X 8
#define UI_GAME_PET_NAME_Y 165

#define UI_GAME_PET_LEVEL_X 8
#define UI_GAME_PET_LEVEL_Y 184

#define UI_GAME_PET_DP_X 8
#define UI_GAME_PET_DP_Y 201

#define UI_GAME_BARS_X 160
#define UI_GAME_BARS_WIDTH 150

#define UI_GAME_HP_TEXT_Y 164
#define UI_GAME_HP_BAR_Y 174
#define UI_GAME_HP_BAR_H 6

#define UI_GAME_EN_TEXT_Y 182
#define UI_GAME_EN_BAR_Y 192
#define UI_GAME_EN_BAR_H 6

#define UI_GAME_XP_TEXT_Y 200
#define UI_GAME_XP_BAR_Y 209
#define UI_GAME_XP_BAR_H 4

#define UI_GAME_STATS_LINE_Y 218

#define UI_GAME_STATS_TEXT_X 10
#define UI_GAME_STATS_TEXT_Y 222

#endif
